### PR TITLE
Update Stable Branch

### PR DESCRIPTION
**Pull request by Rozebot**
Pull patches from master over to stable.

### CODE REVIEW

**Comment by Nekroze** [comment]
failure might be due to go 1.12 release

**Comment by Lachlan-S** [comment]
It seems like the 1.12 release of golang has caused an issue with older versions of `golangci-lint`. In particular `golangci-lint` versions older than 1.12.4 have the same issues, with WARN errors. Whereas versions 1.12.4 and higher seem to not have any issues during a local build.

**Comment by Nekroze** [comment]
Lgtm

**Comment by Lachlan-S** [comment]
lgtm

**Comment by Nekroze** [comment]
just needa final approval review and the docker image to finish updating on the hub

**Comment by Nekroze** [comment]
actually the Docker hub check is not a required check, it just takes a while, since we have both approved I am merging this now.

**Comment by Lachlan-S** [comment]
:+1:

**Pull request merged**
