### PR TITLE
Update apps

### PR DESCRIPTION
**Pull request by deanstalker**
## Change Description

This rather large change brings the existing dab apps up to the current standard (or in some cases, just gets the legacy implementation working - ala kafka/zookeeper)

## Relevant Issue(s)

n/a Maintenance

### CODE REVIEW

**Review by Nekroze — APPROVED** [review]
Great work, much appreciated. Should have some time to look at fixing CI so we don't have to ignore any failures there soon, sorry about that.

**Review by Nekroze — APPROVED** [review]

**Comment by deanstalker** [comment]
No problems, I was getting to the point of setting up a few `@ignore` tags due to not so obvious failures in the smoke tests

**Comment by Nekroze** [comment]
Requires some conflict resolution after the latest merge before I can bring this in

**Comment by deanstalker** [comment]
@Nekroze No probs, I'll sort this out asap

**Comment by deanstalker** [comment]
Conflicts resolved, haven't looked at any issues that have come about due to said conflict resolutions.

**Comment by Nekroze** [comment]
Due to the rebase merge policy on this project (required for the current in app changelog implementation) this PR still results in a merge conflict commit atop the newly added. 

Running a `git rebase upstream/master` should fix the github error when merging assuming a git origin of this repo named `upstream`.

**Pull request merged**
