### PR TITLE
Pin ansible base image for continued py-jinja2 support

### PR DESCRIPTION
**Pull request by blairvbenon**
alpine:latest no longer has support for the py-jinja2 package

## Change Description

Specify last version of alpine that supported py-ninja2 package

## Relevant Issue(s)

- Increment of #
- Closes #
- Fixes #

### CODE REVIEW

**Comment by Nekroze** [comment]
Looks good thanks! Circle CI nodes seem to be flaking today... I will look into this and try retrigger,

**Comment by Nekroze** [comment]
if you could in update the commit message before merging though please, that would be helpful as the git commit message oneliner is used to generate the changelog.

**Comment by Nekroze** [comment]
You have done a merge, not a rebase. You can still perform the rebase and the merge commit will go away. This cannot merge as is as the merge commit will end up as a line item in the changelog.

**Comment by blairvbenon** [comment]
> You have done a merge, not a rebase. You can still perform the rebase and the merge commit will go away. This cannot merge as is as the merge commit will end up as a line item in the changelog.

I don't know how to do that

**Comment by Nekroze** [comment]
There is a comment above that explains why and how to do it but here again are the commands:

```bash
git fetch
git rebase origin/master
```

Assuming origin is this repo and not your fork. Because the git log is used to generate a change log the commit message you have used is also far too generic.

**Comment by blairvbenon** [comment]
I know how to rebase a patch. I can't find a link or figure out how to download the pull request to rebase it. We have done a workaround for this so I'm happy for you to abandon it

**Comment by Nekroze** [comment]
Ah, you will have to add the upstream as a remote:

```bash
git remote add upstream https://github.com/Nekroze/dab
git rebase upstream/master
```

But I will abandon this one and do a new MR with a suitable commit message.

**Pull request closed without merging**
