### PR TITLE
Add Docker Compose v2

### PR DESCRIPTION
**Pull request by slt**
Add docker compose v2
* Install docker compose v2 (docker-cli-compose package)

Tests
* Had troubles with the test or feature that updates the wrapper file. With the file being docker mounted, it was not easily able to update the file in place. I've switched this to mount the containing folder instead which works well.
* Pin mitmproxy version to v6 so the health check works (it needs wget)
* Swapped to official linter images shfmt and golangci-lint rather than using a golangci-lint and installing ourselves
* Updated various shellcheck quoting issues
* Gitter webhook wasn't working so I've dropped it from circleci config

### CODE REVIEW

**Comment by Nekroze** [comment]
Sorry I wasn't able to look at this at all up until now, should be able to give this a good look tonight.

Thanks for the contrib and implication this is still used, I have wanted to give Dab some love and move CI (ideally fix some of the flake too ofc) plus the official image to github itself, feel free to throw anything else that needs doing too: https://github.com/users/Nekroze/projects/1

**Comment by slt** [comment]
Hey no worries, I have still been trying to get it passing the tests anyway 🤞

I've rebased out the merge commits.  

I am just trying to get the "dab network proxy" test working as it fails because there is no longer a curl/wget command in the image for the health check

**Comment by slt** [comment]
Got it passing, had issues with the feature that updates the wrapper file, given its a docker file mount, tried mounting the containing folder instead, that seems to work better, let me know if you are happy with this approach

**Comment by Nekroze** [comment]
yeah looking good, thanks for the contrib!

**Pull request merged**
