### PR TITLE
Update Stable Branch

### PR DESCRIPTION
**Pull request by Rozebot**
Pull patches from master over to stable.

### CODE REVIEW

**Comment by jumbo-grke** [comment]
Hello Nekroze,

Sorry if I have missed some instructions, or if this is a dumb question.

I would like to test this merge, but I don't know how to do so.

My dab currently only works if I set DAB_IMAGE_TAG=stable
Is there a way to set DAB_IMAGE_TAG=something that gives me this merge change?
Or, can I check out this change and build the an image myself?

**Comment by Nekroze** [comment]
@jumbo-grke if you put `DAB_IMGE_TAG` back to unset or latest then you can checkout this version and run `./scripts/build.sh` and then the next dab run will use the image you built locally provided it does not auto update itself. However what you would be testing is master not this PR, the breakage is due to a janky hack in some of your startup scripts abusing the order of ishmael output, switch to a grep as suggested in our gitter and you can use latest again.

**Comment by jumbo-grke** [comment]
Cool, I am able to use dab latest again with the suggested fix.
I am still not sure how to test this specific merge patch though.

Wouldn't ./scripts/build.sh build and use the currently checked out dab?

**Comment by Nekroze** [comment]
This will require a force push I can do tonight or over the weekend. Please signify your approval with a comment here. At least one from each stakeholding user base and I will proceed.

Also RFC on why this has conflicts.

**Comment by Nekroze** [comment]
Because of the rebase only merge strategy, testing the from branch (master in this case) is testing this PR.

**Pull request merged**
